name: dbt_medallion
version: 1.0.0

config-version: 2

profile: snowflake

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  dbt_medallion:
    010_bronze:
      +materialized: view
    020_silver:
      +materialized: incremental
      +unique_key: id
    030_gold:
      +materialized: table
