-- Database ownership
GRANT OWNERSHIP ON DATABASE SALES_DEV
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

-- Schema ownerships
GRANT OWNERSHIP ON SCHEMA SALES_DEV.RAW
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP ON SCHEMA SALES_DEV.BRONZE
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP ON SCHEMA SALES_DEV.SILVER
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP ON SCHEMA SALES_DEV.GOLD
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;


GRANT OWNERSHIP ON DATABASE SALES_QA
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

-- Schema ownerships
GRANT OWNERSHIP ON SCHEMA SALES_QA.RAW
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP ON SCHEMA SALES_QA.BRONZE
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP ON SCHEMA SALES_QA.SILVER
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP ON SCHEMA SALES_QA.GOLD
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP ON DATABASE SALES_PROD
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

-- Schema ownerships
GRANT OWNERSHIP ON SCHEMA SALES_PROD.RAW
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP ON SCHEMA SALES_PROD.BRONZE
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP ON SCHEMA SALES_PROD.SILVER
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP ON SCHEMA SALES_PROD.GOLD
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;