-- Database ownership
GRANT OWNERSHIP ON DATABASE SALES_DEV
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

-- Schema ownerships
GRANT OWNERSHIP ON SCHEMA SALES_DEV.RAW
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP ON SCHEMA SALES_DEV.BRONZE
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP ON SCHEMA SALES_DEV.SILVER
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP ON SCHEMA SALES_DEV.GOLD
TO ROLE ACCOUNTADMIN
COPY CURRENT GRANTS;